---
title: "Day 0: Refresher and intro to dataset"
output: html_document
---

# Potentially useful libraries

```{r, message = FALSE}
library(dplyr)
library(readxl)

df <- read.csv("data/Malaria_Dataset_DataViz.csv")
```

# Exercise 1: Data wrangling

Time to have a first glance at the dataset!
Write a function that:
 1. Only selects the numeric columns that do not end with "id"
 2. Creates a table with the following summary statistics:
  * min, Q1, median, mean, Q3, max
  * the number of NaNs
  * the data type (e.g., ```numeric```)

```{r}
describe <- function(data) {
  # data: A data frame
  # return: Data frame with summary statistics for 'data'

  sub_data <- data %>%
    select_if(is.numeric) %>%
    select(-ends_with("_id"))
  my_summary <- as.data.frame(
    do.call(
      rbind, lapply(
        sub_data, summary
      )
    )
  )
  my_summary$nunique <- c(sub_data %>% summarise_all(n_distinct))
  my_summary$type <- lapply(sub_data, class)
  my_summary$num.na <- lapply(sub_data, function(x) sum(is.na(x)))

  # ////////////////////////////////////////////////////////////
  #                      YOUR CODE HERE
  # ////////////////////////////////////////////////////////////

  my_summary
}
```